name: jboss-cli-windows-bug CI Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        java: ['11','17']
        wildfly-version: ['wildfly2600, wildfly2700']

    steps:
      - name: Checkout cwbug
        uses: actions/checkout@v2
      - name: Checkout wildfly
        if: contains(matrix.wildfly-version, 'wildfly2700')
        uses: actions/checkout@v3
        with:
          repository: wildfly/wildfly
          ref: '27.0.0.Alpha3'
          path: './wildfly'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Build WFLY
        if: contains(matrix.wildfly-version, 'wildfly2700')
        working-directory: ./wildfly
        run: mvn -s ../.m2-settings.xml -DskipTests=true '-Denforcer.skip=true' -Prelease clean install
      - name: Build with Maven Java ${{ matrix.java }} on WildFly ${{ matrix.wildfly-version }}
        run: |
          mvn -s ./.m2-settings.xml -fae --define org.slf4j.simpleLogger.defaultLogLevel=debug -P${{ matrix.wildfly-version }} clean install
      - name: debug file contents
        if: ${{ always() }}
        run: cat ./target/jbws-testsuite-default-elytron-CLI.properties
      - name: CLI LOG contents
        if: ${{ always() }}
        run: cat ./target/jbws-testsuite-default-elytron-CLI.log
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}
          path: '**/surefire-reports/*.*'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}
          path: '**/*/*.log'